namespace com.unity.mgobe.src
{
    public enum ClientSendServerReqWrap2Cmd
    {
        ECmdInvalid = 0,
        ECmdHeartBeatReq = 100,
        ECmdCheckLoginReq = 101,
        ECmdLoginToRoomReq = 102,
        ECmdForwardToRelayReq = 103,
        ECmdLoginReq = 1000,
        ECmdLogoutReq = 1001,
        ECmdAuthReq = 1002,
        ECmdQueryByPlayerIdReq = 1003,
        ECmdQueryByGameIdReq = 1004,
        ECmdGetRoomDetailReq = 2001,
        ECmdJoinRoomReq = 2002,
        ECmdQuitRoomReq = 2003,
        ECmdCreateRoomReq = 2004,
        ECmdDestoryRoomReq = 2005,
        ECmdRemoveMemberReq = 2006,
        ECmdChangeRoomPropertisReq = 2007,
        ECmdDissmissRoomReq = 2008,
        ECmdChangePlayerStateReq = 2009,
        ECmdChangePlayerNetworkStateReq = 2010,
        ECmdRoomChatReq = 2011,
        ECmdStartFrameSyncReq = 2012,
        ECmdStopFrameSyncReq = 2013,
        ECmdGetRoomListReq = 2014,
        ECmdSvrRemoveMemberReq = 2015,
        ECmdSvrChangeRoomPropertisReq = 2016,
        ECmdSvrChangePlayerStateReq = 2017,
        ECmdGetRoomListV2Req = 2018,
        ECmdMatchRoomSimpleReq = 3001,
        ECmdMatchUserSimpleReq = 3002,
        ECmdMatchCancelMatchReq = 3003,
        ECmdMatchRoomComplexReq = 3004,
        ECmdMatchPlayerComplexReq = 3005,
        ECmdRelaySendFrameReq = 4000,
        ECmdRelayRequestFrameReq = 4001,
        ECmdRelayClientSendtoGamesvrReq = 4002,
        ECmdRelayClientRecvFromGamesvrReq = 4003,
        ECmdNotifyJoinRoom = 5000,
        ECmdNotifyQuitRoom = 5001,
        ECmdNotifyDestoryRoom = 5002,
        ECmdNotifyNetState = 5003,
        ECmdNotifyKickMember = 5004,
        ECmdGetAddrByRouterIdReq = 6000
    };


}